[INFO 14:02:57] my_main *******************
[INFO 14:02:57] my_main WANDB RUN ID:
[INFO 14:02:57] my_main 0bqgxl2a
[INFO 14:02:57] my_main *******************
shape of state: 69
shape of observation: 69
[INFO 14:02:59] my_main Beginning training for 20000000.0 timesteps
[INFO 14:02:59] my_main t_env: 600 / 20000000.0
[INFO 14:02:59] my_main Estimated time left: 1 minutes, 49 seconds. Time passed: 0 seconds
/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/stdout_capturing.py:179: UserWarning: tee_stdout.wait timeout. Forcibly terminating.
  warnings.warn("tee_stdout.wait timeout. Forcibly terminating.")
/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/stdout_capturing.py:185: UserWarning: tee_stderr.wait timeout. Forcibly terminating.
  warnings.warn("tee_stderr.wait timeout. Forcibly terminating.")
[DEBUG 14:03:01] pymarl Stopping Heartbeat
[ERROR 14:03:01] pymarl Failed after 0:00:07!
Traceback (most recent calls WITHOUT Sacred internals):
  File "/Users/alexwang/phD/ComplexOvercooked/src/main_debug.py", line 45, in my_main
    run(_run, config, _log)
  File "/Users/alexwang/phD/ComplexOvercooked/src/run.py", line 72, in run
    run_sequential(args=args, logger=logger)
  File "/Users/alexwang/phD/ComplexOvercooked/src/run.py", line 253, in run_sequential
    episode_info = runner.run(test_mode=True)
  File "/Users/alexwang/phD/ComplexOvercooked/src/runners/episode_runner.py", line 106, in run
    if test_mode and self.args.render:
AttributeError: 'types.SimpleNamespace' object has no attribute 'render'. Did you mean: 'runner'?
