[INFO 14:04:17] my_main *******************
[INFO 14:04:17] my_main WANDB RUN ID:
[INFO 14:04:17] my_main tcrqgssc
[INFO 14:04:17] my_main *******************
shape of state: 69
shape of observation: 69
[INFO 14:04:19] my_main Beginning training for 20000000.0 timesteps
[INFO 14:04:19] my_main t_env: 600 / 20000000.0
[INFO 14:04:19] my_main Estimated time left: 1 minutes, 38 seconds. Time passed: 0 seconds
/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/stdout_capturing.py:179: UserWarning: tee_stdout.wait timeout. Forcibly terminating.
  warnings.warn("tee_stdout.wait timeout. Forcibly terminating.")
/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/stdout_capturing.py:185: UserWarning: tee_stderr.wait timeout. Forcibly terminating.
  warnings.warn("tee_stderr.wait timeout. Forcibly terminating.")
[DEBUG 14:04:22] pymarl Stopping Heartbeat
[ERROR 14:04:22] pymarl Failed after 0:00:08!
Traceback (most recent calls WITHOUT Sacred internals):
  File "/Users/alexwang/phD/ComplexOvercooked/src/main_debug.py", line 45, in my_main
    run(_run, config, _log)
  File "/Users/alexwang/phD/ComplexOvercooked/src/run.py", line 72, in run
    run_sequential(args=args, logger=logger)
  File "/Users/alexwang/phD/ComplexOvercooked/src/run.py", line 263, in run_sequential
    args.local_results_path, "models", args.unique_token, "best_model"
AttributeError: 'types.SimpleNamespace' object has no attribute 'local_results_path'
